### ISSUE TITLE
Cosmic mutation frequency information seems limited/arbitrary

### ISSUE THREAD

**Issue by malachig** [SuLab/myvariant.info#20]
Thank you for this amazing resource!

We are in the process of adding selected relevant information from myvariant.info to CIViC (civicdb.org).

While considering options, we hoped to add cosmic mutation frequency.  But the mutation frequency available appears to be the frequency for a single tumor site?  And this is chosen arbitrarily from several possibilities perhaps?

Consider this example (which seem representative of other variants in myvariant.info):
http://myvariant.info/v1/variant/chr7:g.140453136A%3ET

This is BRAF V600E.
http://cancer.sanger.ac.uk/cosmic/mutation/overview?id=476

The mutation frequency information returned for COSMIC is:
    "mut_freq": 2.83,
    "tumor_site": "biliary_tract"

See attached:
<img width="291" alt="myvariant example" src="https://cloud.githubusercontent.com/assets/856728/19394487/0328a434-91ff-11e6-94e7-a050a4c576c2.png">

This seems odd.  How is this being determined?  Would it be possible to determine overall mutation frequency across all tumor_sites, and then for each tumor_site and perhaps return the top site(s) and their frequencies?

Our relevant CIViC github issues are:
https://github.com/genome/civic-server/issues/243
https://github.com/genome/civic-server/issues/38

For now we will move on without using the COSMIC info but it would be great to have more options to select from here.

**Comment by newgene** [comment]
Hi @malachig, due to the license restriction, COSMIC data from MyVariant.info is a pretty old version we took from UCSC, see [their description of comicRaw table](http://www.genome.ucsc.edu/cgi-bin/hgTables?hgsid=547929363_aF7PmK2t9PnaxPVqL84qk3apoj1y&hgta_doSchemaDb=hg19&hgta_doSchemaTable=cosmicRaw). It's from v68 release of COSMIC. I believe, since then, the newer version of COSMIC is not allowed to redistributed, therefore, we cannot include them in MyVariant.info.
