### ISSUE TITLE
query variants with genename

### ISSUE THREAD

**Issue by jma7** [SuLab/myvariant.info#22]
Hi,
   One task I'd like to run with myvariant.info is to return all variants in a gene. For example TP53, so I tried
http://myvariant.info/v1/query?q=TP53&fields=_id
which returns with count of 5918.
I also tried query with ensembleID
http://myvariant.info/v1/query?q=ENSG00000141510&fields=_id
which returns nothing.
Then I tried 
http://myvariant.info/v1/query?q=dbnsfp.ensembl.geneid:ENSG00000141510&fields=_id
http://myvariant.info/v1/query?q=cadd.gene.gene_id:ENSG00000141510&fields=_id
which returns 3318 and 4539.

So the question I have is when I just search for TP53, which fields are searched exactly. It seems the default query in elasticseach is search _all fields? and why I can't get any results back with just ensembleID? Is range query a better way to get all variants related to a gene? Or what is the best way to do this task with myvariant.info api?

Thank you very much

**Comment by newgene** [comment]
@jma7 To query variants with a genename (actually gene symbol), use this query:

http://myvariant.info/v1/query?q=snpeff.ann.genename:TP53&fields=_id

(returns 11559 variants)

When query a gene name using other data source specific field, like dbnsfp.ensembl.geneid or cadd.gene.gene_id, that only returns the matched subset from that data source. Because such a query implies that the matched hits should have dbnsfp or cadd field.

We annotated all variants using snpeff and the annotations are under snpeff field, so querying against these fields will give you the best overall coverage across all data sources.
