### ISSUE TITLE
how to query a position with a POST

### ISSUE THREAD

**Issue by IsmailM** [SuLab/myvariant.info#26]
I would like to query the following variants using POST (i.e. on `http://myvariant.info/v1/query`):

```
q="chr1:54844G>A,chr1:61987A>G,chr1:61989G>C,chr1:86018C>G,chr1:86303G>T"
```
I've tried the above paramaters, but it returns the follows:

```
[
  {
    "query": "chr1:54844G>A",
    "notfound": true
  }
]
```

I understand that I also need to input a scope in order to make it work but I'm not sure what the scope should be in this case...

Thanks
Ismail

**Comment by kevinxin90** [comment]
Hi Ismail,

First, if you want to get annotation information about specific variant or variants, you should use the variant annotation service rather than the query service(GET for one variant, and POST for a list of variants. (http://myvariant.info/v1/api/#MyVariant.info-variant-annotation-services-POST-Variant-annotation-service-via-POST).

Second, you should add 'g.' before the genomic position. Thus, 'chr1:54844G>A' should be changed to chr1:g.54844G>A. So what you need to put in the 'id' field should be: chr1:g.54844G>A,chr1:g.61987A>G,chr1:g.61989G>C,chr1:g.86018C>G,chr1:g.86303G>T.

Also, the default assembly used in myvariant.info is hg19. So if your genomic position is based on hg38, you should try something like, http://myvariant.info/v1/variant/chr11:g.67483235C%3EG?assembly=hg38.

Let us know if you have more questions!

Thanks!
Kevin

**Comment by IsmailM** [comment]
Thanks for the explanation Kevin 👍
